### ISSUE TITLE
Contribute to swift-numerics

### ISSUE THREAD

**Issue by Joannis** [mgriebling/MGDecimal#2]
I saw your comment about contributing to swift-numerics. Is this something you're still interested in?

**Comment by mgriebling** [comment]
Sure, just not sure how to get started.

**Comment by Joannis** [comment]
I think the best way is to reach out to the maintainers through the Swift Open Source Slack. If you need some help with that, please ping me here and I can help you out.

**Comment by mgriebling** [comment]
Hi Joannis, no idea how to get to the Swift Open Source Slack.
